# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: SARIF CI Build
on: 
  push:
    branches-ignore:
     - documentation

jobs:
  build:
    env:
      SARIF_GENERATED_LIB_RELEASE_VERSION: '0.0'
      GEN_LIBRARY_JAVA_VERSION: '1.8'
      
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{env.GEN_LIBRARY_JAVA_VERSION}}
      uses: actions/setup-java@v1
      with:
        java-version: ${{env.GEN_LIBRARY_JAVA_VERSION}}
    
    - name: Build SARIF 2.1.0
      working-directory: ./sarif-2.1.0-generator
      run: ./full-build.sh
      
    # -----------------------------------------
    # Upload Build Artifacts
    # -----------------------------------------
    - name: Archive distribution jar
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: sarif-2.1.0
        path: sarif-2.1.0-generator/gen/sarif-2.1.0/build/libs/
        retention-days: 14